services:
  coredns:
    image: coredns/coredns
    restart: unless-stopped
    volumes:
      - ./Corefile:/etc/coredns/Corefile
    command: -conf /etc/coredns/Corefile
    ports:
      - "${TAILSCALE_IP}:53:53/udp"
      - "${TAILSCALE_IP}:53:53/tcp"
