services:
  dns:
    image: mvance/unbound
    restart: unless-stopped
    volumes:
      - ./unbound.conf:/opt/unbound/etc/unbound/unbound.conf
    ports:
      - "192.168.1.84:53:53/udp"
      - "192.168.1.84:53:53/tcp"
      - "100.119.245.59:53:53/udp"
      - "100.119.245.59:53:53/tcp"
