version: "3.7"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN  # Requerido para modificar interfaces de red
      - SYS_MODULE # Requerido para cargar módulos del kernel
    environment:
      - PUID=1000 # ID de tu usuario (podés verlo con 'id')
      - PGID=1000 # ID de tu grupo (podés verlo con 'id')
      - TZ=America/Argentina/Buenos_Aires # <- CAMBIA ESTO si es necesario
      - SERVERURL=agus-server.duckdns.org # Tu dominio DuckDNS
      - PEERS=1 # Empezá con 1 (para tu Mac). Podés agregar más después.
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules # Requerido para el módulo de WireGuard
    ports:
      # Puerto de WireGuard. DEBE ser UDP
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.ip_forward=1 # Requerido para enrutar el tráfico
    restart: unless-stopped