version: '3.8'
services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./openvpn-data:/etc/openvpn
    restart: unless-stopped